# the port on which the application will go up
server:
  port: 9090

# the git repository that will be used to provide the files that our Configuration Server 
# will make available to the other Microservices via HTTP
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jadsonjs/microservice/config-server 