/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jadson' at '09/04/16 18:53' with Gradle 2.10
 *
 * @author jadson, @date 09/04/16 18:53
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
